import { Router, type IRouter } from "express";
import healthRouter from "./health";
import adsRouter from "./ads";
import statsRouter from "./stats";
import brandingRouter from "./branding";
import adminRouter from "./admin";
import adminUsersRouter from "./admin-users";
import adminStatsRouter from "./admin-stats";
import adminModesRouter from "./admin-modes";
import authRouter from "./auth";
import categoriesRouter from "./categories";
import unitsRouter from "./units";
import promotionPricesRouter from "./promotion-prices";
import plansRouter from "./plans";
import platformConfigRouter from "./platform-config";
import billingRouter from "./billing";
import donationsRouter from "./donations";
import merchantRouter from "./merchant";
import webhookRouter from "./webhook";
import adminPaymentsRouter from "./admin-payments";
import advertisementsRouter from "./advertisements";
import adminProfileRouter from "./admin-profile";
import adminMembersRouter from "./admin-members";
import adminAuditLogRouter from "./admin-audit-log";
import adminExportRouter from "./admin-export";
import announcementsRouter from "./announcements";

const router: IRouter = Router();

router.use(healthRouter);
router.use(adsRouter);
router.use(advertisementsRouter);
router.use(statsRouter);
router.use(brandingRouter);
router.use(adminRouter);
router.use(adminUsersRouter);
router.use(adminStatsRouter);
router.use(adminModesRouter);
router.use(authRouter);
router.use(categoriesRouter);
router.use(unitsRouter);
router.use(promotionPricesRouter);
router.use(plansRouter);
router.use(platformConfigRouter);
router.use(billingRouter);
router.use(donationsRouter);
router.use(merchantRouter);
router.use(webhookRouter);
router.use(adminPaymentsRouter);
router.use(adminProfileRouter);
router.use(adminMembersRouter);
router.use(adminAuditLogRouter);
router.use(adminExportRouter);
router.use(announcementsRouter);

export default router;
